### ISSUE TITLE
This mod disables the Structural Solutions Mod

### ISSUE THREAD

**Issue by Gnasher3i6** [SifVerT/DifficultyTuner#1]
This mod works great, but it disables the build menu for the "Structural Solutions" mod making it unusable.
Pausing or removing this mod makes Structural Solutions available again.

**Comment by SifVerT** [comment]
Hello,

Thanks for the reporting the issue. I've heard the mod Multiply also has an issue with Structural Solutions which does similar things as Difficulty Tuner. Theoretically the mod shouldn't be able to make the build menu disappear for another mod as it handles both vanilla and mod assets the same way unless Structural Solutions uses some unorthodox method which is vulnerable.

Have you used DT to disable the workbench? It may affect the builders.

I've one possible solution, also passing in build categories in the function I use if this is the weakness Structural Solutions has.

**Comment by Gnasher3i6** [comment]
Thanks for the reply.
I have just tried disabling the workbench but the problem still persists.
It most likely is a problem with Structural Solutions as the Zoop function does not work with that mod either (I have to use SMART to bypass that)

I will try report this problem with the other mods author and see if they can make it compatible with this.

Keep up the good work, The modding community is what keeps me playing.

**Comment by SifVerT** [comment]
I've been troubleshooting things and it appears that if player adjusts recipe costs and production on the custom slider this causes everything from Structural Solutions to first become free of cost and if I reload the settings again with a new session every build group of SS disappears. Recipe costs and production uses machines while the stuff with SS uses the build gun so I can't really see why these parameters make SS broken. Building and Milestone cost sliders do not break SS during my testing, nor does any preset difficulty toggle.

If you set Recipe cost and Production to 1.0 (default base game) the SS categories should return, if you restart the game after setting that.

This issue is to 99% certainty caused by Structural Solutions applying some method which DT breaks, because another mod I have like MoreDeco (Factory Props) 'works as intended', DT applies building costs as it should and it allows player to adjust machine recipes. I've heard about other mods having issues with Structural Solutions also. D4rkl0rd isn't a bad dev and is also the dev of Linear Motion, the elevator mod, so there should be some kind of rational solution.

If you can live without machine recipe modification, you can use DT and SS together, because for some reason DT breaks this in SS when modded.

**Comment by SifVerT** [comment]
I've put this issue in my 'known issues' on Difficulty Tuner's Ficsit.app page including the workaround.

**Comment by SifVerT** [comment]
I'll leave the issue open as it's not resolved. Imo the fix is on D4rkL0rd, the dev of Structural Solutions, but I'll check if I can fix it by changing the functions somehow.

**Comment by SifVerT** [comment]
I've optimized the code and Structural Solutions assets aren't vanishing as often, although they can glitch a little but will reappear by changing recipe cost and production sliders and apply. The reason for this is unknown but my improvements seem to have reduced the frequency of the bug.

The mod does by no means disable SS but it glitches to become invisible, particularly if the player changed certain sliders.

**Comment by SifVerT** [comment]
I've helped the dev of Structural Solutions to fix this issue, so i close it as resolved.
